name: NyaaCore
main: cat.nyaa.nyaacore.NyaaCoreLoader
description: "Code infrastructure for all NyaaCat plugins."
version: ${version}
depend:
  - FoliaAdapter
softdepend: [ Essentials ]
load: STARTUP
loadbefore:
  - aolib
authors: [ RecursiveG,Librazy,cyilin ]
website: "https://github.com/NyaaCat/NyaaCore"
api-version: ${api_version}
folia-supported: true